import json
import subprocess
import time
from prometheus_client import Counter, Histogram, Info, start_http_server
from gemma_agent import analyze_log_entry
from action_remediator import ActionRemediator
from notifier import IncidentNotifier

# Prometheus Metrics
REQUESTS_TOTAL = Counter(
    "netflex_http_requests_total",
    "Total HTTP Requests Ingested",
    ["method", "status", "path"]
)
THREATS_DETECTED = Counter(
    "netflex_threats_detected_total",
    "Total Malicious Threats Identified by Gemma 2B",
    ["threat_type", "client_ip"]
)
IPS_BLOCKED_TOTAL = Counter(
    "netflex_ips_blocked_total",
    "Total Malicious IPs Remediated at Ingress"
)
INFERENCE_DURATION = Histogram(
    "netflex_gemma_inference_duration_seconds",
    "Latency of Gemma 2B Classification"
)

# Metric to expose Gemma's text reasoning directly into Grafana tables
INCIDENT_INFO = Info(
    "netflex_security_incident",
    "Real-time SecOps Threat Details Generated by Gemma 2B"
)

def stream_live_nginx_logs():
    remediator = ActionRemediator()
    # Replace None with your Slack/Discord/Webhook URL if you have one
    notifier = IncidentNotifier(webhook_url=None) 

    print("==========================================================")
    print("🛡️ NetFlex AIOps Live Telemetry Watchdog Active")
    print("📊 Metrics & SecOps Feed on http://0.0.0.0:8000/metrics")
    print("🤖 AI Model: Google Gemma 2B (On-Cluster Quantized)")
    print("==========================================================\n")

    cmd = [
        "kubectl", "logs",
        "-n", "ingress-nginx",
        "-l", "app.kubernetes.io/name=ingress-nginx",
        "-c", "controller",
        "-f",
        "--tail=1"
    ]

    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    for line in iter(process.stdout.readline, ''):
        line = line.strip()
        if not line or not line.startswith("{"):
            continue

        try:
            log_data = json.loads(line)
        except json.JSONDecodeError:
            continue

        client_ip = log_data.get("x_forwarded_for") or log_data.get("remote_addr")
        if client_ip and "," in client_ip:
            client_ip = client_ip.split(",")[0].strip()

        path = log_data.get("request_uri", "")
        method = log_data.get("request_method", "GET")
        status = str(log_data.get("status", 200))
        user_agent = log_data.get("http_user_agent", "")

        if "kube-probe" in user_agent or path in ["/healthz", "/metrics"]:
            continue

        REQUESTS_TOTAL.labels(method=method, status=status, path=path).inc()
        print(f"\n[📡 INGESTED TELEMETRY] IP: {client_ip} | Path: {path} | Status: {status} | UA: {user_agent[:40]}...")

        triage_payload = {
            "client_ip": client_ip,
            "path": path,
            "method": method,
            "status_code": status,
            "user_agent": user_agent
        }

        with INFERENCE_DURATION.time():
            decision = analyze_log_entry(triage_payload)

        is_threat = decision.get("is_threat", False)
        threat_type = decision.get("threat_type", "NONE")
        confidence = decision.get("confidence", 0.0)
        reasoning = decision.get("reasoning", "")

        print(f" -> 🤖 Gemma Verdict: Threat={is_threat} ({threat_type}) | Conf={confidence}")
        print(f" -> 🧠 Reason: {reasoning}")

        if is_threat:
            THREATS_DETECTED.labels(threat_type=threat_type, client_ip=client_ip).inc()
            
            # 1. Expose Gemma reasoning to Grafana table
            INCIDENT_INFO.info({
                "client_ip": client_ip,
                "threat_type": threat_type,
                "confidence": f"{confidence * 100:.1f}%",
                "reasoning": reasoning,
                "target_path": path,
                "timestamp": time.strftime("%H:%M:%S UTC")
            })

            # 2. Trigger Auto-Remediation and Brute Force Alert
            if decision.get("recommended_action") == "BLOCK_IP":
                IPS_BLOCKED_TOTAL.inc()
                remediator.block_ip(client_ip, reason=threat_type)
                notifier.emit_alert(client_ip, threat_type, confidence, reasoning)

if __name__ == "__main__":
    start_http_server(8000)
    stream_live_nginx_logs()
