apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflex-smart-gateway
  namespace: netflex-origin
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '100m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - netflex-stream-6787.canadacentral.cloudapp.azure.com
    secretName: netflex-prod-tls
  rules:
  - host: netflex-stream-6787.canadacentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflex-portal
            port:
              number: 8080
      - path: /api/media
        pathType: Prefix
        backend:
          service:
            name: netflex-portal
            port:
              number: 8080
      - path: /admin-trap
        pathType: Prefix
        backend:
          service:
            name: honeypot-trap
            port:
              number: 80
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-api
            port:
              number: 80
